# Example command:
#   Humble on a NVIDIA system:
#   DOCKER_IMAGE=humble-humble-tutorial-source docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source compose run cpu

#  ros2 

services:
  cpu:
    image: moveit/moveit2:main-rolling-tutorial-source
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash

  gpu:
    image: moveit/moveit2:humble-humble-tutorial-source
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: exch
