# Example command:
#   Humble on a NVIDIA system:
#   DOCKER_IMAGE=humble-humble-tutorial-source docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source docker compose run --rm --name moveit2_container cpu
# DOCKER_IMAGE=main-rolling-tutorial-source docker compose run --rm --name moveit2_container gpu

services:
  cpu:
    image: moveit/moveit2:main-rolling-tutorial-source
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: host.docker.internal:0
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

  gpu:
    image: moveit/moveit2:humble-humble-tutorial-source
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY:  host.docker.internal:0
